version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: saechim-zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: saechim-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mysql:
    container_name: saechim_mysql
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=coupon
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
  redis:
    image: redis:latest
    container_name: saechim-redis
    ports:
      - "6379:6379"
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always